---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: kustomize
resources:
- rbac-secretproviderclass.yaml
- csidriver.yaml
- secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
- secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
- secrets-store-csi-driver.yaml
- rbac-secretprovidersyncing.yaml
- rbac-secretproviderrotation.yaml
- rbac-secretprovidertokenrequest.yaml
